language: d

sudo: required

os:
  - linux

d:
 #- dmd # latest
 #- dmd-2.071.2
 - dmd-2.071.1
 #- ldc-1.0.0

script:
  - dub test --compiler=${DC}

addons:
  apt:
    sources:
      - debian-sid

    packages:
      - libsqlite3-0
      - libsqlite3-dev